create or replace TABLE DE6_PROJECT_III.RAW_DATA.SPOTIFY_WEEKLY_CHART (
	BASEDT VARCHAR(8) NOT NULL,
	COUNTRY_CODE VARCHAR(10) NOT NULL,
	MUSIC_ID VARCHAR(50),
	MUSIC_NAME VARCHAR(100),
	MUSIC_RANK NUMBER(8,0) NOT NULL,
	ARTIST_NAME VARCHAR(100),
	primary key (BASEDT, COUNTRY_CODE, MUSIC_RANK)
);