--
CREATE OR REPLACE NETWORK POLICY IP_POLICY
ALLOWED_IP_LIST = ('작업자 IP'...)
BLOCKED_IP_LIST = ();

CREATE DATABASE DE6_PROJECT_III;

CREATE SCHEMA DE6_PROJECT_III.RAW_DATA;
CREATE SCHEMA DE6_PROJECT_III.ANALYTICS;
CREATE SCHEMA DE6_PROJECT_III.ADHOC;

CREATE ROLE PROJECT_ENGINEER;
CREATE ROLE PROJECT_ANALYTICS;

/*
오주언 → OJE
최정우 → CJW
장현우 → JHW
한기중 → HGJ
*/

CREATE USER OJE PASSWORD='PASSWORD';
CREATE USER CJW PASSWORD='PASSWORD';
CREATE USER JHW PASSWORD='PASSWORD';
CREATE USER HGJ PASSWORD='PASSWORD';
CREATE USER BATCH PASSWORD='PASSWORD';
CREATE USER USER_ANALYTICS PASSWORD='PASSWORD';

GRANT ROLE PROJECT_ENGINEER TO USER OJE;
GRANT ROLE PROJECT_ENGINEER TO USER CJW;
GRANT ROLE PROJECT_ENGINEER TO USER JHW;
GRANT ROLE PROJECT_ENGINEER TO USER HGJ;
GRANT ROLE PROJECT_ENGINEER TO USER BATCH;

GRANT ROLE PROJECT_ANALYTICS TO USER USER_ANALYTICS;

--DATABASE/WAREHOUSE/SCHEMA 접근 권한 부여
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO PROJECT_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO PROJECT_ANALYTICS;
GRANT USAGE ON DATABASE DE6_PROJECT_III TO ROLE PROJECT_ENGINEER;
GRANT USAGE ON DATABASE DE6_PROJECT_III TO ROLE PROJECT_ANALYTICS;
GRANT USAGE ON SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT USAGE ON SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ANALYTICS;
GRANT USAGE ON SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT USAGE ON SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ANALYTICS;
GRANT USAGE ON SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;
GRANT USAGE ON SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ANALYTICS;


-- TABLE/VIEW 생성 권한 부여
GRANT CREATE TABLE ON SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT CREATE TABLE ON SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT CREATE TABLE ON SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;
GRANT CREATE VIEW ON SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT CREATE VIEW ON SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT CREATE VIEW ON SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;

-- TABLE DML 권한 부여
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;

--TABLE SELECT 권한 부여
GRANT SELECT ON ALL TABLES IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ANALYTICS;

--VIEW SELECT 권한 부여
GRANT SELECT ON ALL VIEWS IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ENGINEER;

GRANT SELECT ON ALL VIEWS IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON ALL VIEWS IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON ALL VIEWS IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DE6_PROJECT_III.RAW_DATA TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DE6_PROJECT_III.ANALYTICS TO ROLE PROJECT_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DE6_PROJECT_III.ADHOC TO ROLE PROJECT_ANALYTICS;